skip_welcome_message = true

path = [
	# personal
	"/home/ross/bin",
	"/home/ross/local/bin",
	"/home/ross/.local/bin",

	# system
	"/usr/local/bin",
	"/usr/bin",
	"/usr/local/sbin",
	"/usr/sbin",

	# lang
	"/home/ross/.nimble/bin",
	"/home/ross/.cargo/bin",
	"/home/ross/go/bin",
	"/home/ross/.rvm/bin",
	"/home/ross/.gem/ruby/3.0.0/bin",
	"/usr/bin/core_perl",
	"/usr/lib/jvm/java-7-openjdk/jre/bin",

	# domain
	"/home/ross/dev/bin",
	"/home/ross/dev/reaction/bin",
	"/home/ross/dev/mailchimp/bin",
]

startup = [
	"source ./init.nu",
]

[line_editor]
max_history_size = 1048576
completion_match_method = "case-insensitive"
completion_type = "list"
edit_mode = "vi"
tab_stop = 2
show_hints = false

[textview]
tab_width = 2
true_color = true
use_italics = true
vcs_modification_markers = true
pager = "less"
paging_mode = "QuitIfOneScreen"

[env]

##
## settings
##

EDITOR = "nvim"
BROWSER = "google-chrome-stable"
# KEYBOARD = "/dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate-event-kbd"
KEYBOARD = "/dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate-if01-event-kbd"

##
## apps
##

# nodejs
N_PREFIX = "~/local"

# steam
STEAM_COMPAT_DATA_PATH = "/media/data/games/proton/"

# godot
GODOT_BIN = "/usr/bin/godot"

# sensible pagers
PAGER = "less -FRSX"
MANPAGER = "sh -c 'col -bx | bat --language man --plain'"
