require "lib.functions"
require "lib.modes"
require "core"

require "app"
require "buffers"
require "code"
require "copypasta"
require "files"
require "languages"
require "spans"
require "tabs"
require "templates"
require "ui"
require "vcs"
