#!/usr/bin/env bash

# Grabs and prints information about the CPU

read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))

CPU=$((100 * ( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))


echo "$CPU%"

if [ $CPU -ge 90 ]; then
    echo
    echo "#ff0000"
fi
