#!/usr/bin/env bash

# Grabs and prints information about the root hdd

FS="$(df -h / | sed -n '2 p')"; FS=($FS)
echo ' '${FS[5]} ${FS[4]}

if [ ${FS[4]%?} -ge 95 ]; then
    echo
    echo '#47a8e9'
fi
