#!/usr/bin/env bash

# Exit if no player found
players=`playerctl -l`
if [[ ! $players ]]; then exit 0; fi


artist=`playerctl metadata artist`
title=`playerctl metadata title`
album=`playerctl metadata album`
status=`playerctl status`


# Handle when nothing is playing
if [[ ! $title ]]; then
    echo "Nothing playing"
    exit 0
fi


# Determine which status icon to use
declare -A icons
icons=( ["Playing"]="" ["Paused"]="" ["Stopped"]="" )
icon=${icons[$status]}


isPlaying() {
    [[ $status == "Playing" ]]
}


# Add an icon if playing
if isPlaying; then echo -n "  "; fi


echo "$artist - $title, $album $icon"
echo "$artist - $title $icon"


# Use a different color if not playing
if ! isPlaying; then
    echo "#fff000"
fi
