#!/usr/bin/env bash

# exit if no player found
players=`playerctl -l`
if [[ ! $players ]]; then exit 0; fi


artist=`playerctl metadata artist`
title=`playerctl metadata title`
album=`playerctl metadata album`
state=`playerctl status`


isPlaying() {
    [[ $state == "Playing" ]]
}


if isPlaying; then echo -n "  "; fi

echo "$artist - $title, $album [$state]"

if ! isPlaying; then
    echo
    echo "#fff000"
fi
