#!/usr/bin/env bash

interface="${BLOCK_INSTANCE:-eth0}"

netPath=/sys/class/net
interfacePath=`echo $netPath/$interface`

# Expand wildcard interfaces
interface=${interfacePath#$netPath/}

state="$(cat $interfacePath/operstate)"

if [ "$state" != "up" ]; then
	echo "down"
	echo "down"
	echo "#FF0000"
	exit 0
fi

speed="$(cat $interfacePath/speed 2> /dev/null)"

ipaddr="$(ip addr show $interface | perl -n -e'/inet (.+)\// && print $1')"
ipaddr="${ipaddr:-0.0.0.0}"

# full text
echo -n "$ipaddr"
# [ -n "$speed" ] && echo " ($speed Mbits/s)" || echo
[ -n "$speed" ] && echo "" || echo

# short text
echo "$ipaddr"
