#!/usr/bin/env bash

# Grabs and prints information about sound/volume


getVolume() {
    echo `amixer get $BLOCK_INSTANCE | grep "Playback [0-9]* \[" | head -1 | sed -n 's/^[^:]*: Playback [0-9]* \[\([0-9]*\)%\] .*/\1/p'`
}


isMuted() {
    test=`amixer get Master | grep "Playback [0-9]* \[" | head -1 | sed -n 's/^[^:]*: Playback [0-9]* \[\([0-9]*\)%\] \[\([a-z]*\)\]/\2/p'`
    if [[ $test == 'on' ]]; then
        return 1
    else
        return 0
    fi
}


if isMuted; then
    echo "  MUTE"
    echo
    echo "#ff0000"
else
    vol=`getVolume`

    if [ $vol -eq 0 ]; then
        echo " $vol%"
    else
        if [ $vol -le 34 ]; then
            echo " $vol%"
        else
            echo " $vol%"
        fi
    fi
fi


case $BLOCK_BUTTON in
    # right click, mute/unmute
    3) pulseaudio-ctl mute ;;

    # scroll up, increase
    4) pulseaudio-ctl up ;;

    # scroll down, decrease
    5) pulseaudio-ctl down ;;
esac
