#!/usr/bin/env bash

# Grabs and prints information about sound/volume


getVolume() {
    echo `amixer get $BLOCK_INSTANCE | grep -P "Playback \d+ \[" | head -1 | sed -n 's/^[^:]*: Playback [0-9]* \[\([0-9]*\)%\] .*/\1/p'`
}


isMuted() {
    test=`amixer get Master | grep -P "Playback \d+ \[" | head -1 | sed -n 's/^[^:]*: Playback [0-9]* \[\([0-9]*\)%\] \[\([a-z]*\)\]/\2/p'`
    [[ $test != 'on' ]]
}


vol=`getVolume`

if [ $vol -eq 0 ]; then
    icon=
else
    if [ $vol -le 34 ]; then
        icon=
    else
        icon=
    fi
fi

echo "$icon $vol%"

if isMuted; then
    echo
    echo "#ff0000"
fi


case $BLOCK_BUTTON in
    # right click
    # mute/unmute
    3) pulseaudio-ctl mute ;;

    # scroll up
    # raise volume
    4) pulseaudio-ctl up ;;

    # scroll down
    # lower volume
    5) pulseaudio-ctl down ;;
esac


if [[ $BLOCK_BUTTON ]]; then
    pkill -RTMIN+10 i3blocks
fi
