#!/usr/bin/env bash

# Grabs and prints information about sound/volume

vol=$(amixer get $BLOCK_INSTANCE | grep "Playback [0-9]* \[" | head -1 | sed -n 's/^[^:]*: Playback [0-9]* \[\([0-9]*\)%\] .*/\1/p')

if [ $vol -eq 0 ]; then
    echo ' '$vol'%'
else
    if [ $vol -le 34 ]; then
        echo ' '$vol'%'
    else
        echo ' '$vol'%'
    fi
fi
