#!/usr/bin/env bash

# Refresh package lists
yaourt -Syy


arch=$(yaourt -Qu | wc -l)
aurToo=$(yaourt -Qua | wc -l)
aur=$(echo "$aurToo - $arch" | bc)


echo "ARCH: $arch, AUR: $aur"
echo "$arch/$aur"
