" initialize
runtime! config/init.vim

" load packages
runtime! config/packages.vim

" load settings
runtime! config/functions.vim
runtime! config/prefixes.vim
runtime! config/settings.vim
runtime! config/mappings.vim
runtime! config/misc.vim

" load modules
runtime! config/modules/**/*.vim
runtime! config/languages/**/*.vim
runtime! config/plugins/**/*.vim
