" initialize
runtime! config/init.vim

" load packages
runtime! config/packages.vim

" load settings
runtime! config/functions.vim config/prefixes.vim config/settings.vim config/mappings.vim config/misc.vim

" load modules
runtime! config/modules/**/*.vim config/languages/**/*.vim config/plugins/**/*.vim
