#!/usr/bin/env bash

~/bin/bars

# TODO: wtf
sleep 2 && systemctl --user restart sxhkd

# define monitors
bspc monitor -d I II III IV V VI VII VIII IX X XI XII

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
