[Settings]
gtk-font-name = Fairfax Hax HD 12
gtk-theme-name = Catppuccin-Mocha-Standard-Lavender-Dark
gtk-icon-theme-name = Catppuccin-Mocha-Standard-Lavender-Dark
gtk-cursor-theme-name = Catppuccin-Mocha-Lavender-Cursors
gtk-application-prefer-dark-theme = 1
gtk-key-theme-name = Vi
# gtk-key-theme-name = Emacs
